# Generated by Django 3.2 on 2023-05-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230529_0141'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='rating_lte_10',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='score',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(score__lte=10), name='score_lte_10'),
        ),
    ]
